name: GitHub Actions Demo
on: 
  push:
    branches: [main]
    paths-ignore: [.github/**]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "job was triggered by : ${{ github.event_name }}
          echo "name of branch is ${{ github.ref }} and your repository is ."

      - uses: actions/checkout@4.1.1

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files"
          tree
