name: Staged Deployment Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: environment
        options:
          - Test
          - Load-Test
          - Production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: List files
        run: ls -al

  test:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.inputs.environment == 'Test'
    environment: Test
    steps:
      - name: Run Tests
        run: echo "Testing..."

  load-test:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.inputs.environment == 'Load-Test'
    environment: Load-Test
    steps:
      - name: Run Load Tests
        run: |
          echo "Load Testing..."
          sleep 15

  deploy:
    runs-on: ubuntu-latest
    needs: [test, load-test]
    if: github.event.inputs.environment == 'Production'
    environment:
      name: Production
      url: https://writeabout.net
    steps:
      - name: Step 1
        run: |
          echo "Step 1 deploying..."
          sleep 10
      - name: Step 2
        run: |
          echo "Step 2 deploying..."
          sleep 10
      - name: Step 3
        run: |
          echo "Step 3 deploying..."
          sleep 10
      - name: Step 4
        run: |
          echo "Step 4 deploying..."
          sleep 10
      - name: Step 5
        run: |
          echo "Step 5 deploying..."
          sleep 10
